### ISSUE TITLE
A couple of issues

### ISSUE THREAD

**Issue by ToonBasic** [undersquire/Hades#3]
1. Your Anti-Cheat does not use Heuristics, that's a false claim. Though it's open source and free, I won't attack you too much on it. May just wanna reword it, or just remove the claim overall.

2. Why are you using an executor to handle alerts? Refrain from doing that:
[https://github.com/undersquire/Hades/blob/master/src/main/java/me/apex/hades/check/api/Check.java#L41](url)

Just use a Bukkit Runnable on the main thread, refrain from doing it elsewhere.

3. Do not use strings for packets. Very bad idea. That degrades performance. Create your own packet system and make it instance of a specified type rather than just relying on strings to compare them.

4. So much for-looping, that is not good on the CPU. Refrain from doing that and find alternatives.
[https://github.com/undersquire/Hades/blob/master/src/main/java/me/apex/hades/utils/PlayerUtils.java](url)

There's quite a few more issues, but those are just a few to name.

There's a lot of basic Java mistakes being done and does show the lack of knowledge within the area, but I applaud you anyways for making a public, open source, free alternative to other Anti-Cheats.

Feel free to ask me any questions if you wish.

**Comment by undersquire** [comment]
Hello! Thank you for pointing that out! I misunderstood the word "heuristics" :)
I was using an executor because I read somewhere online that executors to increase performance when dealing with all of the flagging/logging. I will test using a runnable to see if its any more performant. As far as for using strings for packets, I can't see how it would degrade performance, if it does then Java needs to be improved. And I am aware of looping in PlayerUtils, and was planning on changing it and hard-coding the utils instead of using nested loops. Thanks for the tips!

**Comment by GladUrBad** [comment]
string comparisons are just slower in general
